### ISSUE TITLE
Importing Simulink model

### ISSUE THREAD

**Issue by ghost** [osate/osate2-plugins#23]
I am trying to import simulink model using but my functional.aadl file does not contain anything related to the simulink model. I am importing an example model form MATLAB R2012a named sf_security.mdl.

**Comment by mohsen1385** [comment]
hi
I want to import my simulink model to osate2 software. but when click on osate>import/export>import simulink model the error is appeared:
please select a directory where the model will created
How can I add my simulink model? Can you guide me step by step?
thanks
