### ISSUE TITLE
Java null pointer exception during instance model traversal (called from resource analysis plugin)

### ISSUE THREAD

**Issue by MikeKonrad** [osate/osate2-plugins#49]
When invoking Analyze Resource Allocations [bound] for processors and memories on [a relatively simple model] (https://gist.github.com/search?q=simplehub3tc10), the plugin crashes, resulting in a call stack (only top few entries shown):

java.lang.NullPointerException
        at org.osate.xtext.aadl2.properties.util.InstanceModelUtil.getEnclosingP
rocessor(InstanceModelUtil.java:467)
        at org.osate.xtext.aadl2.properties.util.InstanceModelUtil.isBoundToProc
essor(InstanceModelUtil.java:356)
        at org.osate.xtext.aadl2.properties.util.InstanceModelUtil.isBoundToProc
essor(InstanceModelUtil.java:366)
        at org.osate.xtext.aadl2.properties.util.InstanceModelUtil$1.suchThat(In
stanceModelUtil.java:575)
        at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.process(For
AllElement.java:270)
        at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreO
rderComponentInstance(ForAllElement.java:642)
        at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreO
rderComponentInstance(ForAllElement.java:647)

From the AADL perspective, the user sees nothing, no error log, nothing to indicate that there was a problem after invoking the analysis plugin.

**Comment by reteprelief** [comment]
Fixed getEnclosingProcessor method. Needed to check for null after retrieving the enclosing component instance.

**Comment by MikeKonrad** [comment]
Whew!!

Thanks,
Mike
