### ISSUE TITLE
FTA Name of Error Event Suggestion for OpenFTA Output

### ISSUE THREAD

**Issue by deyudeng** [osate/osate2-plugins#53]
For OpenFTA output. OpenFTA output names each error event as "event #." Using EMV2::Hazards's HazardTitle or FailureEffect properties, or name of error event event would be nice

[FTA Name of Error Event Suggestion.zip](https://github.com/osate/osate2-plugins/files/157514/FTA.Name.of.Error.Event.Suggestion.zip)

**Comment by deyudeng** [comment]
Forgot to attach sample code. See below.

[CleanedAnalysisTester.zip](https://github.com/osate/osate2-plugins/files/157517/CleanedAnalysisTester.zip)

**Comment by lwrage** [comment]
Export to OpenFTA has been removed from OSATE. A new FTA tool EMFTA is now included.
