### ISSUE TITLE
RBD Self Exlcusion Limitation

### ISSUE THREAD

**Issue by deyudeng** [osate/osate2-plugins#54]
RBD analysis of an implementation does not include the failure rates of the highest level of the heirarchy in its calculations, e.g. if a system's subcomponents have a 50% chance of sending it into state X, and it has a 10% chance of sending itself into state X spontaneously, RBD returns 50% instead of 55%.

See below for example.

[RBD Self Exclusion Limitation.zip](https://github.com/osate/osate2-plugins/files/157520/RBD.Self.Exclusion.Limitation.zip)

**Comment by lwrage** [comment]
RBD was removed from OSATE.
