### ISSUE TITLE
RBD Duplicate Limitation

### ISSUE THREAD

**Issue by deyudeng** [osate/osate2-plugins#55]
Duplicate composite error state declarations are not considered in calculation - listing a single failure case twice causes the RBD algorithm to take it as 2 separate cases, resulting in incorrect probabilities.

See below for examples

[RBD Duplicate Limitation.zip](https://github.com/osate/osate2-plugins/files/157522/RBD.Duplicate.Limitation.zip)

**Comment by lwrage** [comment]
RBD was removed from OSATE.
