### ISSUE TITLE
FTA and RBD Linking Suggestion

### ISSUE THREAD

**Issue by deyudeng** [osate/osate2-plugins#56]
FTA analysis tool pulls from event probability while RBD analysis tool pulls from state probability. Connecting the two (if transitions are already declared) would be useful. E.g. Error X triggers a transition from state A to state B. The probability of state B is not declared, but the probability and distribution of event X is declared. The probability of the system being in state B over that time period is calculable, and being able to have a tool automatically look at that derived probability would be nice.

**Comment by lwrage** [comment]
RBD was removed from OSATE
