### ISSUE TITLE
IMV crashes

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-plugins#58]
When trying to graphically view instance models, IMV crashes at this point:
(line 3168 in Workbench.class)  It's about to invoke:
                    page.setPerspective(targetPerspective);

At the end is the debug stack just before it crashes:
(I followed it around at lower levels, but got lost)

**THE REALLY STRANGE THING IS THAT A .imv FILE IS GENERATED, THAT WHEN OPENED WITH THE Instance Editor, DISPLAYS JUST FINE!**

InstantiateModel.java [EASE Script] 
OSATE2 [Eclipse Application]  
    org.eclipse.equinox.launcher.Main at localhost:57509  
        Thread [main](Suspended %28breakpoint at line 3168 in Workbench%29)  
            Workbench.showPerspective(String, IWorkbenchWindow, IAdaptable) line: 3168  
            Workbench.showPerspective(String, IWorkbenchWindow) line: 3113  
            OpenImvEditor.openImvPerspective() line: 152  
            OpenImvEditor.openImvEditor(NamedElement) line: 77  
            OpenImvEditor.access$0(OpenImvEditor, NamedElement) line: 70  
            OpenImvEditor$1.run() line: 131 
            UISynchronizer(Synchronizer).syncExec(Runnable) line: 186  
            UISynchronizer.syncExec(Runnable) line: 145 
            Display.syncExec(Runnable) line: 4781  
            OpenImvEditor.run(IAction) line: 127  
            ObjectPluginAction(PluginAction).runWithEvent(Event) line: 247  
            PluginActionContributionItem(ActionContributionItem).handleWidgetSelection(Event, boolean) line: 595  
            ActionContributionItem.access$2(ActionContributionItem, Event, boolean) line: 511  
            ActionContributionItem$5.handleEvent(Event) line: 420  
            EventTable.sendEvent(Event) line: 84  
            Display.sendEvent(EventTable, Event) line: 4230 
            MenuItem(Widget).sendEvent(Event) line: 1491  
            MenuItem(Widget).sendEvent(int, Event, boolean) line: 1514  
            MenuItem(Widget).sendEvent(int, Event) line: 1499  
            MenuItem(Widget).notifyListeners(int, Event) line: 1299 
            Display.runDeferredEvents() line: 4072  
            Display.readAndDispatch() line: 3698  
            PartRenderingEngine$4.run() line: 1127  
            Realm.runWithDefault(Realm, Runnable) line: 337 
            PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1018  
            E4Workbench.createAndRunUI(MApplicationElement) line: 156  
            Workbench$5.run() line: 694 
            Realm.runWithDefault(Realm, Runnable) line: 337 
            Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 606  
            PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 150  
            IDEApplication.start(IApplicationContext) line: 139 
            EclipseAppHandle.run(Object) line: 196  
            EclipseAppLauncher.runApplication(Object) line: 134 
            EclipseAppLauncher.start(Object) line: 104  
            EclipseStarter.run(Object) line: 380  
            EclipseStarter.run(String[], Runnable) line: 235  
            NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]  
            NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62  
            DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43  
            Method.invoke(Object, Object...) line: 498  
            Main.invokeFramework(String[], URL[]) line: 669 
            Main.basicRun(String[]) line: 608  
            Main.run(String[]) line: 1515  
            Main.main(String[]) line: 1488  
        Thread [Active Thread: Equinox Container: 0079b79c-2b2e-0016-1d7c-e4368e72e6f1](Running)  
        Daemon Thread [Framework Event Dispatcher: Equinox Container: 0079b79c-2b2e-0016-1d7c-e4368e72e6f1](Running)  
        Daemon Thread [Start Level: Equinox Container: 0079b79c-2b2e-0016-1d7c-e4368e72e6f1](Running)  
        Daemon Thread [[Timer] - Main Queue Handler](Running)  
        Daemon Thread [Bundle File Closer](Running)  
        Thread [Worker-JM](Running)  
        Daemon Thread [EMF Reference Cleaner](Running) 
        Daemon Thread [com.google.inject.internal.util.$Finalizer](Running)  
        Thread [Worker-2](Running) 
        Daemon Thread [Java indexing](Running) 
        Thread [Worker-3](Running) 
        Daemon Thread [EventAdmin Async Event Dispatcher Thread](Running)  
        Thread [Worker-5](Running) 
        Thread [Worker-6](Running) 
        Thread [Worker-8](Running) 
        Thread [Worker-9](Running) 
        Thread [Worker-10](Running)  
        Thread [Worker-12](Running)  
        Thread [Worker-13](Running)  
        Thread [Worker-14](Running)  
        Thread [Worker-18](Running)  
        Thread [Worker-21](Running)  
        Thread [Worker-20](Running)  
        Thread [Worker-22](Running)  
        Thread [Worker-23](Running)  
        Thread [Worker-26](Running)  
        Thread [Worker-27](Running)  
        Daemon Thread [[ThreadPool Manager] - Idle Thread](Running)  
    /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java (Jun 9, 2016, 6:19:11 AM)

**Comment by lwrage** [comment]
The old IMV has been removed from OSATE.
