### ISSUE TITLE
flow latency analysis checks all flows for all modes

### ISSUE THREAD

**Issue by thneumann** [osate/osate2-plugins#59]
I have implemented a small demo model (see .zip), which contains two modes: monitoring & controlling. In addition I specified an end-to-end flow. In the implementation of one component I implemented two flow implementation, one for each mode. I expected to get two results when I do the flow latency analysis for all modes (one result for the monitoring flow and one result for the controlling flow). Actually what I get is a corrupted .xls file (I think there are sheets with the same name which cannot be handled by excel, see .zip file). Finally I get four results (both flows for both modes). However, what I wanted (or expected) to have is one result for the monitoring flow and one result for the controlling flow.

[demoModel.zip](https://github.com/osate/osate2-plugins/files/309028/demoModel.zip)

**Comment by lwrage** [comment]
Fixed, see osate/osate2-core#736
