### ISSUE TITLE
I did not find the Arinc653 Framework in osate2-plugins,but the url about arinc653 framework above wiki pointed here.

### ISSUE THREAD

**Issue by guluo2016** [osate/osate2-plugins#76]

**Comment by sprocter** [comment]
Are the folders Arinc653-basic and Arinc653-misc in https://github.com/osate/examples/tree/master/core-examples what you're looking for?

**Comment by guluo2016** [comment]
> Are the folders Arinc653-basic and Arinc653-misc in https://github.com/osate/examples/tree/master/core-examples what you're looking for?

thank you for you response!I want to find the Arinc653 plugins,but I did not find it anywhere.

**Comment by lwrage** [comment]
The old ARINC653 framework that was mentioned on the wiki is no longer available.
