### ISSUE TITLE
Resolute Errors relating to connections

### ISSUE THREAD

**Issue by dpgluch** [osate/osate2-plugins#96]
I am having problems with claims and prove statements in resolute when using connection references.

[comments and screen capture for the error.docx](https://github.com/osate/osate2-plugins/files/1869238/comments.and.screen.capture.for.the.error.docx)

[test case.txt](https://github.com/osate/osate2-plugins/files/1869222/test.case.txt)

**Comment by dpgluch** [comment]
OSTE version

Version: 2.3.3-SNAPSHOT -- Build id: 2018-03-06

**Comment by lwrage** [comment]
@dpgluch Please do not report issues in osate2-plugins, see #89.
Unfortunately, we can't put this issue tracker in read-only mode.

**Comment by reteprelief** [comment]
addressed by osate/osate2-core#1113
